import type { ButtonPack } from '../types/siteThemes'

export const buttonGroups: Record<string, ButtonPack[]> = {
  vibrant: [
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'square',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'square',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['1em', '0em', '1em', '0em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['1em', '0em', '1em', '0em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['1em', '1em', '0em', '0em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['1em', '1em', '0em', '0em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['vibrant'],
      primary: {
        fill: true,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.25em', y: '0.75em' },
        outline: '2px',
        fontWeight: 500,
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '0.75em' },
        outline: '2px',
        fontWeight: 500,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '2px',
      },
    },
  ],
  neutral: [
    {
      packs: ['neutral'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: true,
        shape: 'pill',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.5em', '0.5em', '0.5em', '0.5em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['neutral'],
      primary: {
        fill: true,
        invert: true,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
    },
  ],
  modern: [
    {
      packs: ['modern'],
      primary: {
        fill: true,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: true,
        shape: 'underline',
        borderRadius: ['1em', '1em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
      tertiary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        fontWeight: 600,
        textTransform: 'uppercase',
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.2em', '0.2em', '0.2em', '0.2em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
    {
      packs: ['modern'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.75em', '0.75em', '0.75em', '0.75em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
        textTransform: 'uppercase',
        fontWeight: 600,
      },
    },
  ],
  minimal: [
    {
      packs: ['minimal'],
      primary: {
        fill: false,
        shape: 'square',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: true,
        invert: true,
        shape: 'square',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: true,
        shape: 'custom',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'custom',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: true,
        shape: 'square',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'square',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
    {
      packs: ['minimal'],
      primary: {
        fill: true,
        invert: true,
        shape: 'pill',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'pill',
        borderRadius: ['0.25em', '0.25em', '0.25em', '0.25em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.5em', y: '1em' },
        outline: '1px',
      },
    },
  ],
  adventurous: [
    {
      packs: ['adventurous'],
      primary: {
        fill: true,
        shape: 'oval',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '0px',
      },
      secondary: {
        fill: false,
        shape: 'oval',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '0px',
      },
    },
    {
      packs: ['adventurous'],
      primary: {
        fill: false,
        shape: 'oval',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      secondary: {
        fill: false,
        shape: 'oval',
        borderRadius: ['1em', '1em', '1em', '1em'],
        padding: { x: '1em', y: '0.75em' },
        outline: '1px',
      },
      tertiary: {
        fill: false,
        shape: 'underline',
        borderRadius: ['0em', '0em', '0em', '0em'],
        padding: { x: '1.25em', y: '1em' },
        outline: '1px',
      },
    },
  ],
}

const buttons: ButtonPack[] = Object.values(buttonGroups).flatMap((array) => array)

export const getButtonPack = (theme: string, index: number): ButtonPack =>
  buttonGroups[theme][index]

export default buttons
